# Generated by Django 5.2.16 on 2026-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classsession_series_id_guardian_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'pending_payment'), ('active', 'active'), ('suspended', 'suspended')], default='pending_payment', max_length=50),
        ),
    ]
