# Generated by Django 5.2.16 on 2026-07-16 11:23

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tenant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_by_guardian_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_by_staff_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.OneToOneField(db_column='guardian_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='api.guardian')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.tenant')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('staff', 'staff'), ('parent', 'parent')], max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('sender_user', models.ForeignKey(blank=True, db_column='sender_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.tenant')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
