# Generated by Django 5.2.16 on 2026-07-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargilycheckout',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chargily_checkouts', to='api.payment'),
        ),
        migrations.AddField(
            model_name='course',
            name='show_on_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='enrollment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargilycheckout',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('annual', 'annual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chargilycheckout',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chargilycheckout',
            name='type',
            field=models.CharField(choices=[('signup', 'signup'), ('renew', 'renew'), ('upgrade', 'upgrade'), ('student_payment', 'student_payment')], default='signup', max_length=50),
        ),
    ]
