# Generated by Django 5.2.16 on 2026-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chargilycheckout_payment_course_show_on_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
