# Generated by Django 5.2.17 on 2026-08-05 10:41

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargilycheckout',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('percent', 'percent'), ('fixed', 'fixed')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicable_plans', models.JSONField(blank=True, default=list)),
                ('max_redemptions', models.IntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.AddField(
            model_name='chargilycheckout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='api.coupon'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tenant')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tenant')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.question')),
            ],
            options={
                'db_table': 'quiz_choices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('closed', 'closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='api.group')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.tenant')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('access_token', models.CharField(default=api.models.generate_uuid, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('not_started', 'not_started'), ('in_progress', 'in_progress'), ('submitted', 'submitted')], default='not_started', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.student')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tenant')),
            ],
            options={
                'db_table': 'quiz_attempts',
                'unique_together': {('quiz', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tenant')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.choice')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.question')),
                ('attempt', models.ForeignKey(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizattempt')),
            ],
            options={
                'db_table': 'quiz_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
