# Generated by Django 5.2.17 on 2026-08-05 20:17

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chargilycheckout_discount_amount_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='show_on_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='map_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SchoolGalleryPhoto',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='api.tenant')),
            ],
            options={
                'db_table': 'school_gallery_photos',
                'ordering': ['order'],
            },
        ),
    ]
