# Generated by Django 5.2.17 on 2026-08-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_teacher_show_on_website_tenant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='solver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
