# Generated by Django 5.2.17 on 2026-08-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_quizattempt_options_and_more'),
    ]

    operations = [
        # tenants.status predates this Django backend (it was a native MySQL
        # ENUM, not a VARCHAR) — Django's CharField AlterField compares
        # db_parameters and sees no change from its own perspective, so it
        # silently skips the ALTER TABLE. Converting the column explicitly is
        # the only way to actually allow the new 'expired' value; the
        # AlterField below then just updates Django's own migration state to
        # match.
        migrations.RunSQL(
            sql="ALTER TABLE tenants MODIFY COLUMN status VARCHAR(50) NOT NULL DEFAULT 'pending_payment';",
            reverse_sql="ALTER TABLE tenants MODIFY COLUMN status ENUM('pending_payment','active','suspended','trial') NOT NULL DEFAULT 'pending_payment';",
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'pending_payment'), ('active', 'active'), ('expired', 'expired'), ('suspended', 'suspended')], default='pending_payment', max_length=50),
        ),
    ]
