# Generated by Django 5.2.17 on 2026-08-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_level',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('middle', 'middle'), ('high', 'high')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
