# Generated by Django 5.2.17 on 2026-08-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_student_id_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='name_latin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_latin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_latin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name_latin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name_latin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
