# Generated by Django 5.2.17 on 2026-08-19 20:22

from django.db import migrations, models


def backfill_pricing_from_duration_weeks(apps, schema_editor):
    """Existing courses were priced as a total split across duration_weeks
    sessions (one session/week, per the old model) — carry that forward as
    an explicit 'fixed_sessions' course rather than silently losing it."""
    Course = apps.get_model('api', 'Course')
    Course.objects.update(pricing_type='fixed_sessions', sessions_count=models.F('duration_weeks'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_guardian_name_latin_student_first_name_latin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_type',
            field=models.CharField(choices=[('per_session', 'per_session'), ('per_month', 'per_month'), ('fixed_sessions', 'fixed_sessions')], default='fixed_sessions', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='sessions_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_pricing_from_duration_weeks, noop),
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='teacher',
            name='cv_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='diploma_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
