# Generated by Django 5.2.17 on 2026-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_course_duration_weeks_course_pricing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='excuse_document_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recovery_status',
            field=models.CharField(choices=[('not_applicable', 'not_applicable'), ('needs_recovery', 'needs_recovery'), ('recovered', 'recovered')], default='not_applicable', max_length=20),
        ),
    ]
