# Generated by Django 5.2.17 on 2026-08-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_attendance_excuse_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='guardian',
            name='source',
            field=models.CharField(choices=[('staff', 'staff'), ('public', 'public')], default='staff', max_length=20),
        ),
    ]
