# Generated by Django 5.2.17 on 2026-08-20 10:54

import api.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_guardian_approval_status_guardian_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='timetable_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('mon', 'mon'), ('tue', 'tue'), ('wed', 'wed'), ('thu', 'thu'), ('fri', 'fri'), ('sat', 'sat'), ('sun', 'sun')], max_length=3)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(choices=[(60, '1h'), (90, '1h30'), (120, '2h'), (180, '3h')], default=60)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(default='#E53935', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.tenant')),
            ],
            options={
                'db_table': 'timetable_entries',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
