# Generated by Django 5.2.17 on 2026-08-24 14:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_tenant_timetable_end_time_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('registration', 'registration'), ('monthly', 'monthly'), ('course', 'course'), ('per_session', 'per_session'), ('trip', 'trip'), ('other', 'other')], default='monthly', max_length=50),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, db_table='trip_student', related_name='trips', to='api.student')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.tenant')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='trip',
            field=models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.trip'),
        ),
    ]
