# Generated by Django 5.2.17 on 2026-08-27 10:55

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_permission_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('registration', 'registration'), ('monthly', 'monthly'), ('course', 'course'), ('per_session', 'per_session'), ('trip', 'trip'), ('book', 'book'), ('other', 'other')], default='monthly', max_length=50),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.tenant')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(blank=True, db_column='book_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.book'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('copy_code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('in_stock', 'in_stock'), ('sold', 'sold')], default='in_stock', max_length=20)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='api.book')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='api.tenant')),
            ],
            options={
                'db_table': 'book_copies',
                'ordering': ['copy_code'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='book_copy',
            field=models.ForeignKey(blank=True, db_column='book_copy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payment', to='api.bookcopy'),
        ),
    ]
