# Generated by Django 5.2.17 on 2026-08-27 11:33

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner_memberships(apps, schema_editor):
    """Every existing owner/director gets a membership row pointing at
    their current tenant, so the multi-school feature works immediately
    for every already-live tenant with zero manual steps — this is purely
    additive and never touches an existing Tenant/User/login row."""
    User = apps.get_model('api', 'User')
    TenantMembership = apps.get_model('api', 'TenantMembership')
    owners = User.objects.filter(role__in=['owner', 'director'], tenant__isnull=False)
    TenantMembership.objects.bulk_create([
        TenantMembership(user_id=u.id, tenant_id=u.tenant_id, role=u.role)
        for u in owners
    ], ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_payment_kind_book_payment_book_bookcopy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(default='owner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.tenant')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_memberships',
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_tenant_membership')],
            },
        ),
        migrations.RunPython(backfill_owner_memberships, noop_reverse),
    ]
