# Generated by Django 5.2.17 on 2026-08-27 12:03

from django.db import migrations, models


def backfill_one_primary_per_user(apps, schema_editor):
    """Every user's earliest membership becomes their principal school —
    for the overwhelming majority (single-school owners) that's their only
    school anyway, so this is a no-op in effect for them and just makes the
    label explicit."""
    TenantMembership = apps.get_model('api', 'TenantMembership')
    seen_users = set()
    for m in TenantMembership.objects.order_by('created_at'):
        if m.user_id not in seen_users:
            m.is_primary = True
            m.save(update_fields=['is_primary'])
            seen_users.add(m.user_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_one_primary_per_user, noop_reverse),
    ]
