# Generated by Django 5.2.17 on 2026-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_tenantmembership_is_primary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'status'], name='attendance_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['tenant', 'book', 'status', 'copy_code'], name='book_copies_stock_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status', 'paid_at'], name='pay_tenant_status_paid_idx'),
        ),
    ]
