# Generated by Django 5.2.17 on 2026-08-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_attendance_attendance_tenant_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='api.room'),
        ),
    ]
