# Generated by Django 5.2.17 on 2026-08-27 22:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


def backfill_one_item_per_payment(apps, schema_editor):
    """Every existing Payment becomes a bill with exactly one PaymentItem,
    carrying over its own kind/course/group/trip/book/book_copy/amount —
    same data, just represented the new way. Payment's own columns are left
    untouched (not read by the app anymore after this migration, but not
    dropped either — see PaymentItem's docstring)."""
    Payment = apps.get_model('api', 'Payment')
    PaymentItem = apps.get_model('api', 'PaymentItem')
    items = [
        PaymentItem(
            id=api.models.generate_uuid(),
            payment_id=p.id,
            kind=p.kind,
            course_id=p.course_id,
            group_id=p.group_id,
            trip_id=p.trip_id,
            book_id=p.book_id,
            book_copy_id=p.book_copy_id,
            amount=p.amount,
        )
        for p in Payment.objects.all()
    ]
    PaymentItem.objects.bulk_create(items, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_timetableentry_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('registration', 'registration'), ('monthly', 'monthly'), ('course', 'course'), ('per_session', 'per_session'), ('trip', 'trip'), ('book', 'book'), ('other', 'other')], default='monthly', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, db_column='book_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='api.book')),
                ('book_copy', models.ForeignKey(blank=True, db_column='book_copy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='api.bookcopy')),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='api.course')),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='api.group')),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.payment')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='api.trip')),
            ],
            options={
                'db_table': 'payment_items',
            },
        ),
        migrations.RunPython(backfill_one_item_per_payment, noop_reverse),
    ]
