# Generated by Django 5.2.17 on 2026-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_paymentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school_level',
            field=models.CharField(blank=True, choices=[('preschool', 'preschool'), ('primary', 'primary'), ('middle', 'middle'), ('high', 'high')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_level',
            field=models.CharField(blank=True, choices=[('preschool', 'preschool'), ('primary', 'primary'), ('middle', 'middle'), ('high', 'high')], max_length=20, null=True),
        ),
    ]
