# Generated by Django 5.2.17 on 2026-09-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_course_school_level_alter_student_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_teacher',
            field=models.ForeignKey(blank=True, db_column='author_teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_books', to='api.teacher'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='teacher_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='book_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
