# Generated by Django 5.2.17 on 2026-09-08 21:32

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_book_author_teacher_payment_school_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtWaiver',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='debt_waivers', to='api.student')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='debt_waivers', to='api.tenant')),
            ],
            options={
                'db_table': 'debt_waivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
