# Generated by Django 5.2.17 on 2026-09-09 21:02, hand-reordered: the
# autogenerated operation order (remove from Payment, then add to
# PaymentItem) would drop existing bill-level percentages before there was
# anywhere to copy them to. This version adds the PaymentItem columns first,
# copies every existing Payment's percentages onto all of its items (the old
# model applied one split uniformly across the whole bill, so copying to
# every item preserves exactly what those bills already meant), then removes
# the now-superseded Payment columns.

import django.core.validators
from django.db import migrations, models


def copy_bill_level_percentages_to_items(apps, schema_editor):
    Payment = apps.get_model('api', 'Payment')
    PaymentItem = apps.get_model('api', 'PaymentItem')
    payments = Payment.objects.filter(
        teacher_percentage__isnull=False,
    ) | Payment.objects.filter(school_percentage__isnull=False)
    for payment in payments.distinct():
        PaymentItem.objects.filter(payment=payment).update(
            teacher_percentage=payment.teacher_percentage,
            school_percentage=payment.school_percentage,
        )


def noop_reverse(apps, schema_editor):
    # Not reversible in a meaningful way (an item-level split can't be
    # collapsed back into one bill-level pair once items can differ) — the
    # schema-reversal operations below still run fine, this just skips
    # trying to reconstruct data that no longer has a single right answer.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_payment_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='school_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='teacher_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RunPython(copy_bill_level_percentages_to_items, noop_reverse),
        migrations.RemoveField(
            model_name='payment',
            name='school_percentage',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='teacher_percentage',
        ),
    ]
