# Generated by Django 5.2.17 on 2026-09-11 10:45

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_payment_school_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='quiz_attempt',
            field=models.OneToOneField(blank=True, db_column='quiz_attempt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='api.quizattempt'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_expense_categories_seeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teacherpayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='ConversationStaffRead',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_reads', to='api.conversation')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_staff_reads',
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
