# Generated by Django 5.2.17 on 2026-09-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_grade_quiz_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('regular', 'regular'), ('standalone', 'standalone')], default='regular', max_length=20),
        ),
    ]
