# Generated by Django 5.2.17 on 2026-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_course_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('regular', 'regular'), ('package', 'package'), ('standalone', 'standalone')], default='regular', max_length=20),
        ),
    ]
