# Generated by Django 5.2.17 on 2026-09-12 19:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_studentinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinsurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
