# Generated by Django on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_studentinsurance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='status',
            field=models.CharField(
                choices=[('paid', 'paid'), ('pending', 'pending')],
                default='paid',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
