# Generated by Django on 2026-09-15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_paymentitem_status_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('paid', 'paid'),
                    ('pending', 'pending'),
                    ('partial', 'partial'),
                    ('pardoned', 'pardoned'),
                    ('refunded', 'refunded'),
                    ('cancelled', 'cancelled'),
                ],
                default='paid',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='amount',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('paid', 'paid'),
                    ('pending', 'pending'),
                    ('partial', 'partial'),
                    ('pardoned', 'pardoned'),
                    ('cancelled', 'cancelled'),
                ],
                default='paid',
                max_length=20,
            ),
        ),
    ]
