# Generated by Django 5.2.17 on 2026-09-15 13:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_payment_status_varchar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinsurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
