# Generated by Django 5.2.17 on 2026-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_expense_amount_alter_teacherpayout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pardon_type',
            field=models.CharField(blank=True, choices=[('both', 'both'), ('school', 'school'), ('teacher', 'teacher')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='pardon_type',
            field=models.CharField(blank=True, choices=[('both', 'both'), ('school', 'school'), ('teacher', 'teacher')], max_length=20, null=True),
        ),
    ]
