# Generated by Django 5.2.17 on 2026-09-16 16:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_payment_pardon_type_paymentitem_pardon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='reduction_target',
            field=models.CharField(choices=[('total', 'total'), ('school', 'school'), ('teacher', 'teacher')], default='total', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='reduction_target',
            field=models.CharField(choices=[('total', 'total'), ('school', 'school'), ('teacher', 'teacher')], default='total', max_length=20),
        ),
    ]
