# Generated by Django 5.2.1 on 2026-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_other_incomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archive_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
